version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - notification-system
    restart: unless-stopped

networks:
  notification-system:
    driver: bridge

volumes:
  grafana:
    driver: local
