global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["127.0.0.1:15672"]
        labels:
          instance: "i-notification-system"
    metrics_path: /api/metrics
    params:
      username: [admin]
      password: [admin]
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:15672
      - source_labels: [__meta_target_label]
        target_label: instance
      - source_labels: []
        target_label: __address__
        replacement: 127.0.0.1:15672
